version: '3.1'
services:
  root:
    ports:
      - "8080:80"
    depends_on:
      - log-handler
      - socket-service
      - eze-handler
  eze-handler:
  log-handler:
    secrets:
      - pg-user
      - pg-pass
      - pg-db
      - pg-host
    environment:
      - PG_USER_FILE=/run/secrets/pg-user
      - PG_HOST_FILE=/run/secrets/pg-host
      - PG_DB_FILE=/run/secrets/pg-db
      - PG_PASS_FILE=/run/secrets/pg-pass
  socket-service:
    ports:
      - "32000:80"
