version: '3.1'
services:
  main:
    image: rosco9awj/ees-datalogger-nginx:v0.2.0
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  eze-handler:
    image: rosco9awj/eze-handler
    deploy:
      restart_policy:
        condition: on-failure
  log-handler:
    image: rosco9awj/log-handler:v1.2.0
    deploy:
      restart_policy:
        condition: on-failure
  historical-service:
    image: rosco9awj/historical-data-service:v1.2.1
    deploy:
      restart_policy:
        condition: on-failure
  accounts-service:
    image: rosco9awj/ees-accounts-service:v1.3.0
    deploy:
      restart_policy:
        condition: on-failure
  socket-service:
    image: rosco9awj/datalogger-socket-service:v1.1.0
    deploy:
      restart_policy:
        condition: on-failure
secrets:
  pg-user:
    external: true
  pg-pass:
    external: true
  pg-host:
    external: true
  pg-db:
    external: true
  ssl_dhparam:
    external: true