version: '3'
services:
  ui-service:
    image: ui-service
    build:
      context: ./ui-service
      args:
        - NODE_ENV=development
    restart: always
    volumes:
      - ./ui-service:/home/node/app
      - ui-service-node-modules:/home/node/app/node_modules
    ports:
      - "8080:80"
      - "81:81"
    networks:
      - frontend
    depends_on:
      - panel-data-api
  panel-data-api:
    build:
      context: ./panel-data-api
      args:
        - NODE_ENV=development
    restart: always
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ./panel-data-api:/opt/app
      - panel-data-node_modules:/opt/app/node_modules
    ports:
      - "9000:80"
    environment:
      - NODE_ENV=development
    networks:
      - frontend
  socket-data:
    build:
      context: ../socketio-databridge
      args:
        - NODE_ENV=development
    restart: always
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../socketio-databridge:/opt/app
      - socket-data-node_modules:/opt/app/node_modules
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    networks:
      - frontend

volumes:
    socket-data-node_modules:
    panel-data-node_modules:
    ui-service-node-modules:

networks:
  frontend:
