version: '3'
services:
  main:
    image: rosco9awj/ees-datalogger-main
    volumes:
      - /etc/ssl/certs/dhparam.pem:/etc/nginx/dhparam.pem
      - /etc/letsencrypt/live/api.voicir.com/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/api.voicir.com/privkey.pem:/etc/nginx/privkey.pem
      - /etc/nginx/snippets/ssl-params.conf:/etc/nginx/ssl-params.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - eze-handler
  eze-handler:
    image: rosco9awj/eze-handler