version: '3.1'
services:
  main:
    image: rosco9awj/ees-datalogger-nginx
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /etc/letsecrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  eze-handler:
    image: rosco9awj/eze-handler
    deploy:
      restart_policy:
        condition: on-failure
  log-handler:
    image: rosco9awj/log-handler
    deploy:
      restart_policy:
        condition: on-failure
  socket-service:
    image: rosco9awj/datalogger-socket-service
    deploy:
      restart_policy:
        condition: on-failure
secrets:
  pg-user:
    external: true
  pg-pass:
    external: true
  pg-host:
    external: true
  pg-db:
    external: true
  ssl_dhparam:
    external: true