version: '3'
services:
  ui-service:
    image: ui-service
    build:
      context: ./ui-service
      args:
        - NODE_ENV=development
    volumes:
      - ./ui-service:/home/node/app
      - ui-service-node-modules:/home/node/app/node_modules
    ports:
      - "8080:80"
      - "81:81"
    networks:
      - frontend
    depends_on:
      - panel-data-api
  panel-data-api:
    build:
      context: ./panel-data-api
      args:
        - NODE_ENV=development
    # you can use legacy debug config or new inspect
    # NOTE: if nodemon isn't restarting on changes, you might be on Windows
    # which has trouble seeing file changes, so add -L to use legacy polling
    # https://github.com/remy/nodemon#application-isnt-restarting
    #command: ../node_modules/.bin/nodemon --debug=0.0.0.0:5858
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229
    volumes:
      - ./panel-data-api:/opt/app
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_modules location. Thanks to PR from @brnluiz
      - notused:/opt/app/node_modules
    ports:
      - "9000:80"
    environment:
      - NODE_ENV=development
    networks:
      - frontend
  panel-data-api:
    build:
      context: ./panel-data-api
      args:
        - NODE_ENV=development
    # you can use legacy debug config or new inspect
    # NOTE: if nodemon isn't restarting on changes, you might be on Windows
    # which has trouble seeing file changes, so add -L to use legacy polling
    # https://github.com/remy/nodemon#application-isnt-restarting
    #command: ../node_modules/.bin/nodemon --debug=0.0.0.0:5858
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229
    volumes:
      - ./panel-data-api:/opt/app
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_modules location. Thanks to PR from @brnluiz
      - panel-data-node_modules:/opt/app/node_modules
    ports:
      - "9000:80"
    environment:
      - NODE_ENV=development
    networks:
      - frontend
  socket-data:
    build:
      context: ./socket-data
      args:
        - NODE_ENV=development
    # you can use legacy debug config or new inspect
    # NOTE: if nodemon isn't restarting on changes, you might be on Windows
    # which has trouble seeing file changes, so add -L to use legacy polling
    # https://github.com/remy/nodemon#application-isnt-restarting
    #command: ../node_modules/.bin/nodemon --debug=0.0.0.0:5858
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ./socket-data:/opt/app
      - socket-data-node_modules:/opt/app/node_modules
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    networks:
      - frontend

volumes:
    socket-data-node_modules:
    panel-data-node_modules:
    ui-service-node-modules:

networks:
  frontend:
