version: '3.1'
services:
  main:
    image: rosco9awj/ees-datalogger-main
    secrets:
      - letsencrypt_fullchain
      - letsencrypt_privkey
      - ssl_dhparam
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - eze-handler
    networks:
      - ees-datalogger
  eze-handler:
    image: rosco9awj/eze-handler
    networks:
      - ees-datalogger

networks:
  ees-datalogger:

secrets:
  letsencrypt_fullchain:
    external: true
  letsencrypt_privkey:
    external: true
  ssl_dhparam:
    external: true   "bbvwysj21jxbl0xk0ss3frliy" "azhjm7iymhh287qc3xd1g0xzx"