version: '3.1'
services:
  main:
    image: rosco9awj/ees-datalogger-main
    secrets:
      - letsencrypt_fullchain
      - letsencrypt_privkey
      - ssl_dhparam
    environment:
      LETSENCRYPT_FULLCHAIN_PATH: /run/secrets/letsencrypt_fullchain
      LETSENCRYPT_PRIVKEY_PATH: /run/secrets/letsencrypt_privkey
      SSL_DHPARAM_PATH: /run/secrets/ssl_dhparam
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - eze-handler
  eze-handler:
    image: rosco9awj/eze-handler

secrets:
  letsencrypt_fullchain:
    external: letsencrypt_fullchain
  letsencrypt_privkey:
    external: letsencrypt_privkey
  ssl_dhparam:
    external: ssl_dhparam