version: '3.1'
services:
  main:
    secrets:
      - ssl_dhparam
    image: rosco9awj/oee-master-nginx:v0.8.0
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  health:
    image: rosco9awj/oee-master-health:v0.8.0
    deploy:
      restart_policy:
        condition: on-failure
  point-logs:
    image: rosco9awj/oee-master-point-logs:v0.8.0
    deploy:
      restart_policy:
        condition: on-failure
  graphs:
    image: rosco9awj/oee-master-graphs:v0.8.0
    deploy:
      restart_policy:
        condition: on-failure
  accounts:
    image: rosco9awj/oee-master-accounts:v0.8.0
    deploy:
      restart_policy:
        condition: on-failure
  live-data:
    image: rosco9awj/oee-master-live-data:v0.8.0
    deploy:
      restart_policy:
        condition: on-failure
  alerts:
    image: rosco9awj/oee-master-alerts:v0.8.0
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - pg-user
      - pg-pass
      - pg-db
      - pg-host
      - twilio-sid
      - twilio-auth-token
      - twilio-phone-num
    environment:
      - PG_USER_FILE=/run/secrets/pg-user
      - PG_HOST_FILE=/run/secrets/pg-host
      - PG_DB_FILE=/run/secrets/pg-db
      - PG_PASS_FILE=/run/secrets/pg-pass
      - TWILIO_SID=/run/secrets/twilio-sid
      - TWILIO_AUTH_TOKEN=/run/secrets/twilio-auth-token
      - TWILIO_PHONE_NUM=/run/secrets/twilio-phone-num
secrets:
  pg-user:
    external: true
  pg-pass:
    external: true
  pg-host:
    external: true
  pg-db:
    external: true
  jwt-secret:
    external: true
  ssl_dhparam:
    external: true
  twilio-sid:
    external: true
  twilio-auth-token:
    external: true
  twilio-phone-num:
    external: true
