version: '3.1'
services:
  main:
    image: rosco9awj/oee-master-nginx:v0.7.3
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  health-service:
    image: rosco9awj/oee-master-health-service:v0.7.3
    deploy:
      restart_policy:
        condition: on-failure
  log-handler:
    image: rosco9awj/oee-master-log-handler:v0.7.3
    deploy:
      restart_policy:
        condition: on-failure
  historical-service:
    image: rosco9awj/oee-master-historical-service:v0.7.3
    deploy:
      restart_policy:
        condition: on-failure
  accounts-service:
    image: rosco9awj/oee-master-accounts-service:v0.7.3
    deploy:
      restart_policy:
        condition: on-failure
  socket-service:
    image: rosco9awj/oee-master-socket-service:v0.7.3
    deploy:
      restart_policy:
        condition: on-failure
  alerts-service:
    image: rosco9awj/oee-master-alerts-service:v0.7.3
    deploy:
      restart_policy:
        condition: on-failure
secrets:
  pg-user:
    external: true
  pg-pass:
    external: true
  pg-host:
    external: true
  pg-db:
    external: true
  ssl_dhparam:
    external: true
  twilio-sid:
    external: true
  twilio-auth-token:
    external: true
  twilio-phone-num:
    external: true
