secrets:
  pg-db:
    external: true
  pg-host:
    external: true
  pg-pass:
    external: true
  pg-user:
    external: true
  ssl_dhparam:
    external: true
services:
  accounts-service:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PG_DB_FILE: /run/secrets/pg-db
      PG_HOST_FILE: /run/secrets/pg-host
      PG_PASS_FILE: /run/secrets/pg-pass
      PG_USER_FILE: /run/secrets/pg-user
    image: rosco9awj/oee-master-accounts-service:v0.4.2
    secrets:
    - source: pg-db
    - source: pg-host
    - source: pg-pass
    - source: pg-user
  historical-service:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PG_DB_FILE: /run/secrets/pg-db
      PG_HOST_FILE: /run/secrets/pg-host
      PG_PASS_FILE: /run/secrets/pg-pass
      PG_USER_FILE: /run/secrets/pg-user
    image: rosco9awj/oee-master-historical-service:v0.4.2
    secrets:
    - source: pg-db
    - source: pg-host
    - source: pg-pass
    - source: pg-user
  log-handler:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PG_DB_FILE: /run/secrets/pg-db
      PG_HOST_FILE: /run/secrets/pg-host
      PG_PASS_FILE: /run/secrets/pg-pass
      PG_USER_FILE: /run/secrets/pg-user
    image: rosco9awj/oee-master-log-handler:v0.4.2
    secrets:
    - source: pg-db
    - source: pg-host
    - source: pg-pass
    - source: pg-user
  main:
    depends_on:
    - historical-service
    - log-handler
    - socket-service
    deploy:
      restart_policy:
        condition: on-failure
    image: rosco9awj/oee-master-nginx:v0.4.2
    ports:
    - 80:80/tcp
    - 443:443/tcp
    secrets:
    - source: ssl_dhparam
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:rw
  socket-service:
    deploy:
      restart_policy:
        condition: on-failure
    image: rosco9awj/oee-master-socket-service:v0.4.2
    ports:
    - 32000:80/tcp
version: '3.1'

