secrets:
  jwt-secret:
    external: true
  pg-db:
    external: true
  pg-host:
    external: true
  pg-pass:
    external: true
  pg-user:
    external: true
  ssl_dhparam:
    external: true
  twilio-auth-token:
    external: true
  twilio-phone-num:
    external: true
  twilio-sid:
    external: true
services:
  accounts-service:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt-secret
      PG_DB_FILE: /run/secrets/pg-db
      PG_HOST_FILE: /run/secrets/pg-host
      PG_PASS_FILE: /run/secrets/pg-pass
      PG_USER_FILE: /run/secrets/pg-user
    image: rosco9awj/oee-master-accounts-service:v0.8.0
    secrets:
    - source: jwt-secret
    - source: pg-db
    - source: pg-host
    - source: pg-pass
    - source: pg-user
  alerts-service:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PG_DB_FILE: /run/secrets/pg-db
      PG_HOST_FILE: /run/secrets/pg-host
      PG_PASS_FILE: /run/secrets/pg-pass
      PG_USER_FILE: /run/secrets/pg-user
      TWILIO_AUTH_TOKEN: /run/secrets/twilio-auth-token
      TWILIO_PHONE_NUM: /run/secrets/twilio-phone-num
      TWILIO_SID: /run/secrets/twilio-sid
    image: rosco9awj/oee-master-alerts-service:v0.8.0
    secrets:
    - source: pg-db
    - source: pg-host
    - source: pg-pass
    - source: pg-user
    - source: twilio-auth-token
    - source: twilio-phone-num
    - source: twilio-sid
  health-service:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PG_DB_FILE: /run/secrets/pg-db
      PG_HOST_FILE: /run/secrets/pg-host
      PG_PASS_FILE: /run/secrets/pg-pass
      PG_USER_FILE: /run/secrets/pg-user
      TWILIO_AUTH_TOKEN: /run/secrets/twilio-auth-token
      TWILIO_PHONE_NUM: /run/secrets/twilio-phone-num
      TWILIO_SID: /run/secrets/twilio-sid
    image: rosco9awj/oee-master-health-service:v0.8.0
    secrets:
    - source: pg-db
    - source: pg-host
    - source: pg-pass
    - source: pg-user
    - source: twilio-auth-token
    - source: twilio-phone-num
    - source: twilio-sid
  historical-service:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PG_DB_FILE: /run/secrets/pg-db
      PG_HOST_FILE: /run/secrets/pg-host
      PG_PASS_FILE: /run/secrets/pg-pass
      PG_USER_FILE: /run/secrets/pg-user
    image: rosco9awj/oee-master-historical-service:v0.8.0
    secrets:
    - source: pg-db
    - source: pg-host
    - source: pg-pass
    - source: pg-user
  log-handler:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PG_DB_FILE: /run/secrets/pg-db
      PG_HOST_FILE: /run/secrets/pg-host
      PG_PASS_FILE: /run/secrets/pg-pass
      PG_USER_FILE: /run/secrets/pg-user
    image: rosco9awj/oee-master-log-handler:v0.8.0
    secrets:
    - source: pg-db
    - source: pg-host
    - source: pg-pass
    - source: pg-user
  main:
    depends_on:
    - historical-service
    - log-handler
    - socket-service
    deploy:
      restart_policy:
        condition: on-failure
    image: rosco9awj/oee-master-nginx:v0.8.0
    ports:
    - 80:80/tcp
    - 443:443/tcp
    secrets:
    - source: ssl_dhparam
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:rw
  socket-service:
    deploy:
      restart_policy:
        condition: on-failure
    image: rosco9awj/oee-master-socket-service:v0.8.0
    ports:
    - 32000:80/tcp
version: '3.1'

