version: '3.1'
services:
  main:
    secrets:
      - ssl_dhparam
    depends_on:
      - log-handler
      - socket-service
      - historical-service
  health-service:
    secrets:
      - pg-user
      - pg-pass
      - pg-db
      - pg-host
    environment:
      - PG_USER_FILE=/run/secrets/pg-user
      - PG_HOST_FILE=/run/secrets/pg-host
      - PG_DB_FILE=/run/secrets/pg-db
      - PG_PASS_FILE=/run/secrets/pg-pass
  log-handler:
    secrets:
      - pg-user
      - pg-pass
      - pg-db
      - pg-host
    environment:
      - PG_USER_FILE=/run/secrets/pg-user
      - PG_HOST_FILE=/run/secrets/pg-host
      - PG_DB_FILE=/run/secrets/pg-db
      - PG_PASS_FILE=/run/secrets/pg-pass
  historical-service:
    secrets:
      - pg-user
      - pg-pass
      - pg-db
      - pg-host
    environment:
      - PG_USER_FILE=/run/secrets/pg-user
      - PG_HOST_FILE=/run/secrets/pg-host
      - PG_DB_FILE=/run/secrets/pg-db
      - PG_PASS_FILE=/run/secrets/pg-pass
  accounts-service:
    secrets:
      - pg-user
      - pg-pass
      - pg-db
      - pg-host
    environment:
      - PG_USER_FILE=/run/secrets/pg-user
      - PG_HOST_FILE=/run/secrets/pg-host
      - PG_DB_FILE=/run/secrets/pg-db
      - PG_PASS_FILE=/run/secrets/pg-pass
  socket-service:
    ports:
      - "32000:80"
  alerts-service:
    secrets:
      - pg-user
      - pg-pass
      - pg-db
      - pg-host
      - twilio-sid
      - twilio-auth-token
      - twilio-phone-num
    environment:
      - PG_USER_FILE=/run/secrets/pg-user
      - PG_HOST_FILE=/run/secrets/pg-host
      - PG_DB_FILE=/run/secrets/pg-db
      - PG_PASS_FILE=/run/secrets/pg-pass
      - TWILIO_SID=/run/secrets/twilio-sid
      - TWILIO_AUTH_TOKEN=/run/secrets/twilio-auth-token
      - TWILIO_PHONE_NUM=/run/secrets/twilio-phone-num
