version: '3.1'

services:
  main:
    build:
      context: ../nginx
    ports:
      - "8080:80"
    volumes:
      - ../nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./dev-keys/ssl:/etc/ssl
  health-service:
    build:
      context: ../health-service
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../health-service:/opt/app
      - health-service-node_modules:/opt/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
  log-handler:
    build:
      context: ../log-handler
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../log-handler:/opt/app
      - log-handler-node_modules:/opt/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
  historical-service:
    build:
      context: ../historical-service
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../historical-service:/opt/app
      - historical-service-node_modules:/opt/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
  accounts-service:
    build:
      context: ../accounts-service
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../accounts-service:/opt/app
      - accounts-service-node_modules:/opt/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
  socket-service:
    build:
      context: ../socket-service
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../socket-service:/opt/app
      - socket-data-node_modules:/opt/app/node_modules
  alerts-service:
    build:
      context: ../alerts-service
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../alerts-service:/opt/app
      - alerts-node_modules:/opt/app/node_modules
  postgres:
    image: postgres
    restart: always
    ports:
      - "32768:5432"
    environment:
      POSTGRES_PASSWORD: password
volumes:
  socket-data-node_modules:
  alerts-node_modules:
  log-handler-node_modules:
  health-service-node_modules:
  historical-service-node_modules:
  accounts-service-node_modules:
secrets:
  pg-user:
    file: dev-keys/pg-user.txt
  pg-pass:
    file: dev-keys/pg-pass.txt
  pg-host:
    file: dev-keys/pg-host.txt
  pg-db:
    file: dev-keys/pg-db.txt
  twilio-sid:
    file: ../../../../../../Desktop/twilio/sid.txt
  twilio-auth-token:
    file: ../../../../../../Desktop/twilio/auth_token.txt
  twilio-phone-num:
    file: ../../../../../../Desktop/twilio/phone_num.txt
  ssl_dhparam:
    file: dev-keys/ssl/dhparam.pem