// Node Cache
var node_cache = require('node-cache');

const FULL_DAY_IN_SECONDS = 86400;
const FOUR_HOURS_IN_SECONDS = 3600 * 4;

const DELETE_CACHED_ITEM_AFTER_X_SECONDS = FULL_DAY_IN_SECONDS;
const CHECK_FOR_OLD_CACHE_ITEMS_AFTER_X_SECONDS = FOUR_HOURS_IN_SECONDS;

export const PRIMARY_CACHE = new node_cache({
	stdTTL: DELETE_CACHED_ITEM_AFTER_X_SECONDS,
	checkperiod:  CHECK_FOR_OLD_CACHE_ITEMS_AFTER_X_SECONDS
});
