version: '3.1'

services:
  main:
    build:
      context: ../server/nginx
    ports:
      - "8080:80"
    volumes:
      - ../server/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./dev-keys/ssl:/etc/ssl
  log-handler:
    build:
      context: ../server/log-handler
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../server/log-handler:/opt/app
      - log-handler-node_modules:/opt/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
  historical-service:
    build:
      context: ../server/historical-service
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../server/historical-service:/opt/app
      - historical-service-node_modules:/opt/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
  accounts-service:
    build:
      context: ../server/accounts-service
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../server/accounts-service:/opt/app
      - accounts-service-node_modules:/opt/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
  socket-service:
    build:
      context: ../server/socket-service
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    volumes:
      - ../server/socket-service:/opt/app
      - socket-data-node_modules:/opt/app/node_modules
  postgres:
    image: postgres
    restart: always
    ports:
      - "32768:5432"
    environment:
      POSTGRES_PASSWORD: password
volumes:
  socket-data-node_modules:
  log-handler-node_modules:
  historical-service-node_modules:
  accounts-service-node_modules:
secrets:
  pg-user:
    file: dev-keys/pg-user.txt
  pg-pass:
    file: dev-keys/pg-pass.txt
  pg-host:
    file: dev-keys/pg-host.txt
  pg-db:
    file: dev-keys/pg-db.txt
  ssl_dhparam:
    file: dev-keys/ssl/dhparam.pem