export const NEW_LOG = 'NEW_LOG';
export const REMOVE_POINTS = 'REMOVE_POINTS';
export const MULTISELECT_POINT = 'MULTISELECT_POINT';
export const MULTISELECT_DESELECT_POINT = 'MULTISELECT_DESELECT_POINT';